@startuml 構想

(練習参加人数の増加) <-- (既存プレイヤー層を\nさらに楽しませたい):how

(カバディを普及させたい) --> (既存プレイヤー層を\nさらに楽しませたい):why

(プレイヤーの増加) <-- (カバディを普及させたい):how
(ファン・観客数の増加) <-- (カバディを普及させたい):how

(体験会開催数の増加) <-- (プレイヤーの増加):how

(公式戦広報) <-- (ファン・観客数の増加):how

(練習参加人数の増加) <- (プレイヤーの増加):commit

(既存プレイヤー層を\nさらに楽しませたい) --> (公式戦をLIVE配信) : how

(プレイヤーのハイレベル化) <- (既存プレイヤー層を\nさらに楽しませたい):how

(公式戦をLIVE配信) ->(演出) : 品質

(公式戦をLIVE配信) -->(実況者) : 品質

(演出) -> (スコアテロップ) : 例

(演出) --> (スローリプレイ) : 例

(公式戦をLIVE配信) --> (映像の解像度) : 品質

(スタッツデータの\nアーカイブ) <- (公式戦をLIVE配信):commit

(プレイヤーのハイレベル化) --> (スタッツデータの\nアーカイブ):ref

(練習の質向上) <-- (プレイヤーのハイレベル化):how


(頻度) <- (練習参加人数の増加):要因
(拠点の確保しやすさ) <-- (頻度)

(頻度) <-- (練習の質向上):要因

(プレイヤーの増加) <-- (公式戦をLIVE配信) : effect

(チーム主体の\nトライアウト) <-- (プレイヤーの増加)
@enduml